### ISSUE TITLE
Introducing Stub Code

### ISSUE THREAD

**Issue by pdamian** [cyber-defence-campus/morion#5]
**Tasks:**
- [x] Create binary stub code for the `strlen` function (ARMv7, position-independent)
- [ ] Compare `strlen` implementations of `glibc`, `uClibc-ng` and stub in Triton core
- [x] Use `morion`'s hooking mechanism instead of the (future) stubs within Triton's core
- [x] Use `morion`'s hooking mechanism instead of patching the PLT
- [x] Create some tests

**References:**
- https://github.com/JonathanSalwan/Triton/issues/1156#issue-1299699552
- https://github.com/JonathanSalwan/Triton/blob/dev-v1.0/src/stubs/triton-stubs.c
